sonar.projectKey=test-wallet
sonar.projectName=Test Wallet
sonar.projectVersion=0.0.1

sonar.sources=src
sonar.sourceEncoding=UTF-8

sonar.exclusions=src/generated/**,**/*.spec.ts,node_modules/**

sonar.language=typescript

sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.coverage.exclusions=src/generated/**,**/*.spec.ts,**/*.module.ts,src/main.ts,src/index.html

sonar.projectBaseDir=.

