# SPDX-FileCopyrightText: 2025 Swiss Confederation
#
# SPDX-License-Identifier: MIT

# Inspired by https://thomasthornton.cloud/2025/03/18/setting-up-trivy-in-your-github-actions/
name: Pull Request Check
run-name: ${{ github.repository }} is evaluating pull request
on: [pull_request]

permissions:
  actions: read
  security-events: write
  contents: read
  packages: write
  attestations: write
  id-token: write
  pull-requests: write  # allow coverage comment

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.20.x

      - name: Install dependencies
        run: |
          npm ci --legacy-peer-deps --no-audit --no-fund

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript-typescript
          config-file: ./.github/codeql/codeql-config.yml

      - name: Run Angular build
        run: npm run build

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:javascript-typescript"

      - name: Run ESLint static analysis
        id: eslint
        run: npm run lint 2>&1 | tee eslint-report.txt || true
        continue-on-error: true

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.30.0
        with:
          scan-type: fs
          scan-ref: .
          scanners: vuln,config,secret
          severity: CRITICAL,HIGH
          exit-code: 0
          format: sarif
          output: trivy-results.sarif

      - name: Upload Trivy SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        continue-on-error: true
        with:
          sarif_file: trivy-results.sarif
          category: trivy-scan
